In [2]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np


In [13]:
m1 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])


print(m1)


print(" ===============")
m2 = np.array([[0,2,3],
[8,15,6],
[7,8,2]])

print(m2)


print(" ===============")
print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  2  3]
 [ 8 15  6]
 [ 7  8  2]]
[[ 37  56  21]
 [ 82 131  54]
 [127 206  87]]


In [14]:
s = np.array(5)
print(s.ndim)

0


In [31]:
class Student:

    def __init__(self, name):
        self.name = name
    @property
    def get_info(self):
    
        return f"my name is {self.name}"

In [32]:
s1 = Student("hashem")
s1.get_info

'my name is hashem'

In [34]:
vec_1 = np.array([1,2,3,4,5,6])
mat_1 = vec_1.reshape(3,2)
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
def reshape_mat(mat,x,y):
    mat = vec_1.reshape(x,y)
    return mat


In [42]:
mat_1=reshape_mat(mat_1,3,2)
print(mat_1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
vec_2 = np.array([1,2,3,4])
vec_2.shape[0]


5

In [54]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2.reshape(vec_2.shape[0],1)
print(mat_2)

[[1]
 [2]
 [3]
 [4]]


In [50]:
def reshape_col_vec(mat):
    mat = vec_1.reshape((mat.shape[0],1))
    return mat



In [71]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2[:,None ]
print(mat_2)

[[1]
 [2]
 [3]
 [4]]


In [68]:
mat_3 =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9.8]
])
print(mat_3.dtype)
print(mat_3)

float64
[[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.8]]


In [72]:
mat_4 =np.array([
    [True,False,True],
    [True,True,6],
    
])
print(mat_4.dtype)
print(mat_4)

int64
[[1 0 1]
 [1 1 6]]


In [ ]:
mat_5 = np.array([
        [1.1,'2',3],
        [4,5,6.2],
        [7,8,9.2]])
print(mat_5.dtype)
print(mat_5)

<U32
[['1.1' '2' '3']
 ['4' '5' '6.2']
 ['7' '8' '9.2']]


In [76]:
class C:
    x=3
o1 =C()

In [79]:
mat_6 = np.array([
        [1.1,'2',3],
        [4,5,6.2],
        [4,8,9.2]])
print(mat_6.dtype)
print(mat_6)

<U32
[['1.1' '2' '3']
 ['4' '5' '6.2']
 ['4' '8' '9.2']]


In [81]:
f_mat=mat_6.astype(float)
f_mat

array([[1.1, 2. , 3. ],
       [4. , 5. , 6.2],
       [4. , 8. , 9.2]])

In [83]:
v1= np.array([1,2,3,4,5])
v1[1]

np.int64(2)

In [85]:
f_mat

array([[1.1, 2. , 3. ],
       [4. , 5. , 6.2],
       [4. , 8. , 9.2]])

In [84]:
f_mat[1,2]

np.float64(6.2)

In [89]:
mat_7 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [0,0,0]])
mat_7[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [90]:
mat_7.T

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [92]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
mat = np.full((3,3),4)
mat

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [99]:
mat =np.empty((3,3))
mat

array([[1.1, 2. , 3. ],
       [4. , 5. , 6.2],
       [4. , 8. , 9.2]])

In [100]:
angels =np.arange(0,361,90)

angels

array([  0,  90, 180, 270, 360])

In [102]:
def image_rotate(angel):
    return angel

In [103]:
vec = np.linspace(0,10,num=10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])